### PR TITLE
[BFCL] add ibm-granite-20b-functioncallling model

### PR DESCRIPTION
**Pull request by MayankAgarwal**
This PR adds the [granite-20b-functioncalling](https://huggingface.co/ibm-granite/granite-20b-functioncalling) model to the BFCL.

This PR only adds the model handler. The leaderboard should be updated in a separate PR.

### CODE REVIEW

**Comment by HuanzhiMao** [comment]
Thank you for the PR @MayankAgarwal ! We will review and test it, and update the leaderboard accordingly.

**Review by HuanzhiMao — APPROVED** [review]
Hey @MayankAgarwal, 

I noticed that you intentionally removed the language-specific hint we included at the end of the model prompt [here](https://github.com/ShishirPatil/gorilla/pull/525/files#diff-64c3e18612454d570980d67c9ddfdeb2195acd2538e68d7630205fbda2388ebdR28-R33). I'm wondering what's the reasoning behind this change? 

In my opinion, this removal could negatively impact the model's performance, especially in the Java and JavaScript test categories. However, we are fine with the removal as it won't unfairly benefit the model. I just want to bring this to your attention.

The rest of the PR looks great!

**Comment by MayankAgarwal** [comment]
Hi @HuanzhiMao,

Thank you for reviewing and approving the PR. 

We chose to remove the language-specific prompt augmentation because of the following reasons:
1. Since we unified the input and output format to JSON for this model, we were not sure of including any language-specific hint in the prompt. I believe that unless the model outputs code in that specific language (say Java or JavaScript in the case of BFCL), there should be a separate process to convert the function-calling output from a model to that specific language, rather than the model itself generating language-compliant code in JSON/XML data format.
2. We did not add the language-specific hint in the prompt while experimenting with other tasks and datasets. Thus, to maintain consistency we did not include it in this PR, and
4. While building the model handler, we experimented with both adding and removing the language-specific hint and we did not see a significant difference in the performance.

Owing to these reasons, we decided to remove the language-specific hint. I hope these sound reasonable to you.

If there are no changes from your side, please merge the PR. I would love to see the model on the leaderboard.

Thanks again for reviewing the PR!

**Comment by ShishirPatil** [comment]
Thank you for the PR @MayankAgarwal  and delighted to welcome IBM models into the BFCL!

**Pull request merged**
