### PR TITLE
[BFCL Dataset Revamp 5/n] Multi-Turn Base WrapUp

### PR DESCRIPTION
**Pull request by Fanjia-Yan**
This PR continues https://github.com/ShishirPatil/gorilla/pull/737 a 2-week initiative to re-scrutinize across V3 dataset issues with several objectives:

1. Enforce int + float compatibility.
2. Remove duplicated functions.
3. Clean several entries.

### CODE REVIEW

**Comment by CharlieJCJ** [comment]
@Fanjia-Yan What's the testings on this, does it pass all ground truth unit tests/

**Comment by Fanjia-Yan** [comment]
@HuanzhiMao Updated the `add_to_watchlist` function `stock` parameter.

**Review by HuanzhiMao — APPROVED** [review]
LGTM

**Review by CharlieJCJ — APPROVED** [review]
LGTM

**Pull request merged**
