### PR TITLE
added yfinance api to api zoo

### PR DESCRIPTION
**Pull request by raywanb**
The 'yfinance API' has been integrated into the API Zoo. To fetch historical market data, users can use the 'yfinance.Ticker()' function by providing the stock ticker symbol of their choice. This API allows users to access a wide array of financial data, including stock price, dividends, splits, news, options, and income statements. The 'yfinance API' simplifies data retrieval and analysis for stocks.

### CODE REVIEW

**Comment by ShishirPatil** [comment]
Thanks for the PR @raywanb. Can you add your github handle for all the "user_name" fields? Also quick question - is this an exhaustive list of the APIs that yfinance offers? Rest looks good!

**Comment by raywanb** [comment]
@ShishirPatil fixed. Yea, this pretty much encompasses all of yfinances' apis.

**Comment by ShishirPatil** [comment]
Also, quick question - is there a reason why all API versions are "1.0"? I think the current pypi version is at 0.2.36 as per https://pypi.org/project/yfinance/

**Comment by raywanb** [comment]
Nope, fixed it

**Review by ShishirPatil — APPROVED** [review]
LGTM! Thanks for the PR @raywanb 🎉

**Pull request merged**
