### PR TITLE
Add NousResearch Hermes models to no cost models list

### PR DESCRIPTION
**Pull request by alonsosilvaallende**
Add NousResearch Hermes models to no cost models list

### CODE REVIEW

**Review by HuanzhiMao — COMMENTED** [review]
Hi @alonsosilvaallende, 
The Hermes model should not be added to the `NO_COST_MODELS` list. 
We use the following formula to estimate the cost and latency for locally-hosted models. image 
Since the Hermes model can be loaded into 8 x V100 machines, it will have the `Cost` and `Latency` fields computed as above.

**Comment by alonsosilvaallende** [comment]
Thank you very much for your explanation @HuanzhiMao 
What does 'no cost' mean? I see that Salesforce/xLAM-7b-fc-r has no cost. Does that mean the cost could not be determined?

**Comment by HuanzhiMao** [comment]
> Thank you very much for your explanation @HuanzhiMao What does 'no cost' mean? I see that Salesforce/xLAM-7b-fc-r has no cost. Does that mean the cost could not be determined?

Yes, because the xLAM model cannot be loaded into 8 x V100 machines (`bfloat16` is not compatible with V100). See [here](https://github.com/ShishirPatil/gorilla/pull/532#issuecomment-2251559211).

**Comment by alonsosilvaallende** [comment]
I understand. The name was misleading me. Last question: Also the functionary small models meetkai/functionary-small-v2.4 cannot be run on 8 x V100 machines?

**Comment by HuanzhiMao** [comment]
> I understand. The name was misleading me. Last question: Also the functionary small models meetkai/functionary-small-v2.4 cannot be run on 8 x V100 machines?

Yes, you are right. `functionary-small` does require `bfloat16`. We will fix it.

**Pull request closed without merging**
