### PR TITLE
Fixes For NexusHandler

### PR DESCRIPTION
**Pull request by VenkatKS**
Hello! 

I just had a chance to take a look at the handler code for one of the open source models for Raven, and noticed a few things that could be fixed. I have made some fixes here, including fixes for converting the typescript Function Calling DSL into Python Function Calling DSL. This PR is for fixing the prompting issues only.

I believe this logic can be used for other Prompt-based models as well. I notice you ask the model to generate Python outputs but give JSON inputs for prompt-based FC; this can be applied to standardize the prompting side for these other models as well.

I believe there are further fixes necessary on the AST parsing of the outputs that can further improve the performance of the model. Happy to help contribute more there!

I ran the model with these changes, and these are the new results I notice: 

| Category        | REPORTED | UPDATED |
|-----------------|----------|---------|
| Simple AST      | 68.91    | 80.5    |
| Multiple AST    | 76       | 86      |
| Parallel AST    | 30.5     | 42      |
| Parallel Multiple | 43.5    | 49      |
| Simple Exec     | 64.12    | 95      |
| Multiple Exec   | 82       | 92      |
| Parallel Exec   | 46       | 74      |
| Parallel Multiple I | 55    | 62.5    |
| Relevance       | 2.08     | 57.5    |
| **AVG**         | **52.01222222** | **70.94444444** |

Here are the results JSONs for each of the above with the new runs:
1. Simple AST: [simple_score.json](https://github.com/ShishirPatil/gorilla/files/15380677/simple_score.json)
2. Multiple AST: 
[multiple_function_score.json](https://github.com/ShishirPatil/gorilla/files/15380683/multiple_function_score.json)
3. Parallel AST: 
[parallel_function_score.json](https://github.com/ShishirPatil/gorilla/files/15380686/parallel_function_score.json)
4. Parallel Multiple AST: 
[parallel_multiple_function_score.json](https://github.com/ShishirPatil/gorilla/files/15380691/parallel_multiple_function_score.json)
5. Simple Exec: 
[executable_simple_score.json](https://github.com/ShishirPatil/gorilla/files/15380694/executable_simple_score.json)
6. Multiple Exec: 
[executable_multiple_function_score.json](https://github.com/ShishirPatil/gorilla/files/15380696/executable_multiple_function_score.json)
7. Parallel Exec: 
[executable_parallel_function_score.json](https://github.com/ShishirPatil/gorilla/files/15380699/executable_parallel_function_score.json)
8. Parallel Multiple Exec: 
[executable_parallel_multiple_function_score.json](https://github.com/ShishirPatil/gorilla/files/15380700/executable_parallel_multiple_function_score.json)
9. Relevancy Score: 
[relevance_score.json](https://github.com/ShishirPatil/gorilla/files/15380703/relevance_score.json)

The average result improves by around 19% with these fixes, and likely can improve more with more fixes on the AST side to eliminate false negatives. 

Regarding the AST fixes, there are several category of errors. For one of the errors, as an example, please consider this:
```python
"model_result_decoded": [{"calculate_resistance": {"length": 5, "area": 0.01}}, {"calculate_resistance": {"length": 5, "area": 0.01, "resistivity": "aluminum"}}], "possible_answer": {"calculate_resistance_1": {"length": [5], "area": [0.01], "resistivity": ["copper"]}, "calculate_resistance_2": {"length": [5], "area": [0.01], "resistivity": ["aluminum"]}}}
```
It appears that the model has generated `calculate_resistance(5, 0.01); calculate_resistance(5, 0.01, "aluminium")` but the ground truth is `calculate_resistance(5, 0.01, "copper"); calculate_resistance(5, 0.01, "aluminium")`, and therefore it is marked as wrong. But for Pythonic DSL, the default values need not be generated, as "copper" is specified as the default for this argument: `"resistivity": {"type": "string", "description": "Resistivity of the material (Default: 'copper'). Allowed values: 'copper', 'aluminum'"}}`. This is emblematic of other AST issues that might need to be fixed as well, and can move accuracy higher to reflect the real performance.

These AST issues might need to be fixed in another PR.

Very excited for the amazing work you have done here -- it is truly a very comprehensive leaderboard! 

Thank you so much!

### CODE REVIEW

**Comment by HuanzhiMao** [comment]
Hi @VenkatKS,

Thanks for your contribution!

We will take a look at your handler patch later this week. We are a bit busy with the paper deadline at the moment :/ 

Regarding the AST issue you mentioned above, I agree that `calculate_resistance(5, 0.01, "copper");` should indeed be correct. This is an oversight on our end for the possible answers. We will address this issue in the next release by updating the possible answers. You are also welcome to make a PR if you would like to contribute :)

**Comment by venkats-nexusflow** [comment]
Thanks @HuanzhiMao! 

No rush at all, best of luck with your paper!

**Review by HuanzhiMao — APPROVED** [review]
Hey @VenkatKS,

Sorry for the delay in reply and thanks for the fix. This patch looks good to me. We will merge it and update the leaderboard score shortly.

Best,
Huanzhi

**Comment by CharlieJCJ** [comment]
Here is a quick FYI.

In your table in PR description, for `REPORTED` and `UPDATED`, our `REPORTED` numbers for simple ast and simple exec on https://gorilla.cs.berkeley.edu/leaderboard.html are weighted average of several sub-categories (including java, javascript, rest api) written in this section 
image in https://gorilla.cs.berkeley.edu/blogs/8_berkeley_function_calling_leaderboard.html#categories. 

So, the updated score shown in leaderboard in #472 will also take account of java, javascript, rest api categories' results, which will have a slightly different number from your PR description. We're currently finalizing numbers.

**Pull request merged**
