### PR TITLE
BFCL April 19th Release (Dataset & Pipeline)

### LINKED ISSUE #363: Leaderboard evaluations issues
Hi,

First of all, I really appreciate your work!

I've been trying to run the leaderboard evaluation code, and noted several issues. I can probably fix some of them on my own in a PR, but wanted to hear your thought before that.

1. Specificity of argument description. In several functions, I noted that the description of the parameters is not explicit enough, which results in the models being evaluated sometimes outputting the "wrong" parameters. Attached are a few examples.

In this function, it isn't mentioned that `interest_rate` shouldn't be the number of percents (that is, 3.5 instead of 0.035 for example):
```python
def mortgage_calculator(loan_amount, interest_rate, loan_period):
    """
    Calculates the monthly mortgage payment.
    Args:
        loan_amount (integer): The amount of the loan.
        interest_rate (integer): The interest rate of the loan.
        loan_period (integer): The period of the loan.
    """
    monthly_interest_rate = interest_rate / 12
    number_of_payments = loan_period * 12
    monthly_payment = (
        loan_amount
        * monthly_interest_rate
        * (1 + monthly_interest_rate) ** number_of_payments
        / ((1 + monthly_interest_rate) ** number_of_payments - 1)
    )
    return monthly_payment
```

In this example, it isn't mentioned that the `stock_name` should be a ticker symbol and not the company's name:
```python
def get_company_name_by_stock_name(stock_name):
    """
    Finds the company name of a stock by its stock name.
    Args:
        stock_name (str): The stock name of the product.
    """
    url = "https://yahoo-finance15.p.rapidapi.com/api/v1/markets/search"

    querystring = {"search": stock_name}

    headers = {
        "X-RapidAPI-Key": api_key["RAPID-API-KEY"],
        "X-RapidAPI-Host": "yahoo-finance15.p.rapidapi.com",
    }

    response = requests.get(url, headers=headers, params=querystring)
    try:
        return response.json()["body"][0]["name"]
    except:
        return response.json()
```

2. Hard typing constraints.
For example, one of the questions in `gorilla_openfunctions_v1_test_executable_multiple_function.json` is `As a data analyst, you are working on a project that requires you to organize a set of numerical data. Can you sort these numbers 34, 2, 56, 7, 9, 12 in descending order?`, where the description of the relavant function is:
```json
{
  "name": "sort_array",
  "description": "Sorts an array of numbers.",
  "parameters": {
    "type": "dict",
    "properties": {
      "array": {
        "type": "array",
        "items": {
          "type": "float"
        },
        "description": "The array of numbers."
      },
      "reverse": {
        "type": "boolean",
        "description": "Whether to sort the array in reverse order.",
        "default": false
      }
    },
    "required": [
      "array"
    ]
  }
}
```
Since the given numbers are all integers, there shouldn't be a problem in sending them to the function as ints, rather than floats. Generally speaking, I think the typing constraints on floats should also be able to accept ints, as long as their values as correct.

3. Several incorrect "gold" answers. For example, in `gorilla_openfunctions_v1_test_executable_simple.json`, one of the questions is `Book a king room of 10000 dollar from Dec.11,2023, to Aug.15,2024, with customer id 123.`, while the gold answer states that the value of `total_price` should be 1000, rather than 10000.

I also found a few cases where the list of values in "possible_answer" wasn't exhaustive enough, but I can't find any specific example right now.

Thanks in advance!

### PR DESCRIPTION
**Pull request by HuanzhiMao**
This PR is for the BFCL April 19th Release. In this release:

- Bug fix for the evaluation dataset in the executable test categories. This includes updates to both prompts and function docs. 
- The `evaluation_result` field has been removed to accommodate the variability in API execution results across different evaluation runs. Instead, a human-verified `ground_truth` is now included for the executable test categories. During each evaluation run, `evaluation_result` is generated anew using the `ground_truth`, and then compared against the model output. 
- A stricter metric has been adopted when using the `structural_match` (aka. type match) evaluation criteria ---- For `list` results, the lengths are compared; for `dict` results, the keys are matched. This is to account for the fast-changing nature of some of the real-time API results while ensuring the evaluation remains meaningful.
- Added another evaluation criterion `real_time_match` for the executable category, which is a looser form of `exact_match` specifically for numerical execution results. The execution result must be within a certain percentage threshold (20%) from the expected result to accommodate the live updates of API responses. Users can change this threshold value in `eval_checker_constant.py`.
- Added support to distinguish Cohere's optimized score vs. original score.
- Resolved #363 

This PR **DOES** change the leaderboard score. We will update the leaderboard shortly, in a different PR. 
We will also update our HuggingFace dataset accordingly.

---------

Co-authored-by: Charlie Cheng-Jie Ji <charliechengjieji@berkeley.edu>
Co-authored-by: Fanjia Yan <fanjiayan@berkeley.edu>

### CODE REVIEW

**Comment by CharlieJCJ** [comment]
WIP: Undergoing thorough testing

**Comment by CharlieJCJ** [comment]
Fully tested on model-generated results
- API sanity check (Non-REST and REST)
- `python ./eval_runner.py` on all categories (i.e. ast and executable)

Action Taken:
- improved Rapid API stability during both sanity check and real-time execution to allow max_retry during the function calls.

**Review by CharlieJCJ — APPROVED** [review]
LGTM

**Review by ShishirPatil — APPROVED** [review]
LGTM

**Pull request merged**
