### PR TITLE
[Update Gemini-1.0-Pro result checker]

### PR DESCRIPTION
**Pull request by Fanjia-Yan**
This PR adds checker for Gemini-1.0-pro result. I have tested on AST and Executable test suite to make sure that the statistics and result of leaderboard matches.

### CODE REVIEW

**Review by ShishirPatil — APPROVED** [review]
LGTM

**Comment by ShishirPatil** [comment]
Hey @vandyxiaowei let us know if you have any thoughts on this!

**Comment by vandyxiaowei** [comment]
Thank you for addressing this! How about the code to run against Gemini model? Or do you want me to refactor my PR https://github.com/ShishirPatil/gorilla/pull/234 a bit and merge that?

**Comment by ShishirPatil** [comment]
Hey @vandyxiaowei Yes! That sounds like a great idea.

**Pull request merged**
