### PR TITLE
Fix breaking changes due to updated Anthropic SDK

### PR DESCRIPTION
**Pull request by eitanturok**
Anthropic just moved their tool use from beta to main so we have to change the import `from anthropic.types.beta.tools import ToolUseBlock` to `from anthropic.types import ToolUseBlock`. You cannot run the eval without this change as things break.

Also, my IDE automatically sorted the imported packages and removed some extra spaces -- this explains all the other changes.

### CODE REVIEW

**Comment by eitanturok** [comment]
@justinwangx, @HuanzhiMao

**Review by HuanzhiMao — APPROVED** [review]
Thanks for the PR @eitanturok!

@ShishirPatil LGTM, ready to merge.

**Comment by eitanturok** [comment]
Also, this situation would be avoided if you pin your package versions. As a best practice, might be worthwhile doing this...

**Comment by HuanzhiMao** [comment]
> Also, this situation would be avoided if you pin your package versions. As a best practice, might be worthwhile doing this...

Yes, good point. We will add that.

**Review by ShishirPatil — APPROVED** [review]
LGTM. Thanks @eitanturok

**Pull request merged**
