### PR TITLE
[BFCL] Leaderboard Update - 2024/12/29 (Checkpoint 0cea216)

### PR DESCRIPTION
**Pull request by HuanzhiMao**
This PR updates the leaderboard to reflect the change in score due to the following PR merge:

1. #822 
2. #826 
3. #829 
4. #832 
5. #837 
6. #840 
7. #835 
8. #842 
9.  #843 
10. #846 
11. #838 
12. #847 
13. #855 
14. #857 

Models were evaluated using checkpoint commit 0cea216.

### CODE REVIEW

**Comment by CharlieJCJ** [comment]
DIFF of 12/06 and 12/29
changes_heatmap
live_acc_table_heatmap
non-live_ast_acc_table_heatmap
multi_turn_acc_table_heatmap

**Comment by HuanzhiMao** [comment]
Update: This leaderboard update will exclude the `BitAgent/GoGoAgent` as their endpoint seems to be erroring out. cc @RogueTensor

**Comment by CharlieJCJ** [comment]
<details>
<summary>DIFF of 12/06 and 12/29</summary>

changes_heatmap

</details>

<details>
<summary>Live Accuracy Table</summary>

live_acc_table_heatmap

</details>

<details>
<summary>Non-Live AST Accuracy Table</summary>

non-live_ast_acc_table_heatmap

</details>
<details>
<summary>Non-Live Exec Accuracy Table</summary>

non-live_exec_acc_table_heatmap

</details>

<details>
<summary>Multi-Turn Accuracy Table</summary>

multi_turn_acc_table_heatmap
</details>

**Review by CharlieJCJ — COMMENTED** [review]
Reviewed all numbers, LGTM

**Review by CharlieJCJ — APPROVED** [review]

**Pull request merged**
