### PR TITLE
[BFCL] Standardize TEST_CATEGORY Among eval_runner.py and openfunctions_evaluation.py

### PR DESCRIPTION
**Pull request by HuanzhiMao**
There are inconsistencies between the `test_category` argument that's used by `eval_checker/eval_runner.py` and `openfunctions_evaluation.py`. 

This PR partially addresses #501 and #502.

### CODE REVIEW

**Review by CharlieJCJ — APPROVED** [review]
LGTM

Comment: improve error message, make them more information for user to know immediate action items when aggregating results for `data.csv`.

**Comment by HuanzhiMao** [comment]
> LGTM
> 
> Comment: improve warning message in the future, make them more information for user to know immediate action items when aggregating results for `data.csv`.

Good point. Will address this in a different PR.

**Comment by ShishirPatil** [comment]
Hey @HuanzhiMao and @CharlieJCJ I don't think this is a great idea for the following reason. So we start by showing how to install the dependencies, and then in the middle we go into a long extempore on the different flags and then we come back with a list of commands to run. This ain't helpful back and forth? Maybe we retain the previous structure where after each command we show the options so users have the context on the command. Thoughts?

**Comment by HuanzhiMao** [comment]
> Hey @HuanzhiMao and @CharlieJCJ I don't think this is a great idea for the following reason. So we start by showing how to install the dependencies, and then in the middle we go into a long extempore on the different flags and then we come back with a list of commands to run. This ain't helpful back and forth? Maybe we retain the previous structure where after each command we show the options so users have the context on the command. Thoughts?

How about we move the flags section to the bottom of the README, just like how all the available model names are displayed at the end?

**Comment by devanshamin** [comment]
I have solved this issue [here](https://github.com/ShishirPatil/gorilla/pull/510/commits/c7c51672a5516553e3af32714ee134985504ac52).

**Comment by ShishirPatil** [comment]
> > Hey @HuanzhiMao and @CharlieJCJ I don't think this is a great idea for the following reason. So we start by showing how to install the dependencies, and then in the middle we go into a long extempore on the different flags and then we come back with a list of commands to run. This ain't helpful back and forth? Maybe we retain the previous structure where after each command we show the options so users have the context on the command. Thoughts?
> 
> How about we move the flags section to the bottom of the README, just like how all the available model names are displayed at the end?

I don't think this solves it right? We should present the flags when the user cares about the command, not super down. Folks read and execute code from READMEs linearly, and making them jump around isn't a good idea imo.

**Review by ShishirPatil — APPROVED** [review]

**Pull request merged**
