### PR TITLE
[BFCL] Add New Model functionary-small-v3.1, functionary-small-v3.2, functionary-medium-v3.1; Update Token Price

### PR DESCRIPTION
**Pull request by HuanzhiMao**
Add the following new models:

- `meetkai/functionary-small-v3.1-FC`
- `meetkai/functionary-small-v3.2-FC`
- `meetkai/functionary-medium-v3.1-FC`

We will update the leaderboard shortly, in a different PR.

### CODE REVIEW

**Comment by khai-meetkai** [comment]
Thank you, can you also evaluate our new 70b:
[meetkai/functionary-medium-v3.1](https://huggingface.co/meetkai/functionary-medium-v3.1)

**Comment by HuanzhiMao** [comment]
@khai-meetkai Do you want to keep both `functionary-medium-v3.0-FC` and `functionary-medium-v3.1-FC` or just upgrade `functionary-medium-v3.0-FC` to `functionary-medium-v3.1-FC` ?

**Comment by khai-meetkai** [comment]
> @khai-meetkai Do you want to keep both `functionary-medium-v3.0-FC` and `functionary-medium-v3.1-FC` or just upgrade `functionary-medium-v3.0-FC` to `functionary-medium-v3.1-FC` ?

I think `functionary-medium-v3.1-FC` is enough so please ignore: functionary-medium-v3.0-FC

**Review by CharlieJCJ — APPROVED** [review]
LGTM

**Review by ShishirPatil — APPROVED** [review]

**Pull request merged**
