### PR TITLE
add a basic bfcl command-line interface

### PR DESCRIPTION
**Pull request by mattf**
add a simple cli wrapping openfunctions_evaluation.py (`bfcl run`) and eval_runner.py (`bfcl evaluate`).

```
➜ bfcl
                                                                                                                             
 Usage: bfcl [OPTIONS] COMMAND [ARGS]...                                                                                     
                                                                                                                             
╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --install-completion            Install completion for the current shell.                                                 │
│ --show-completion               Show completion for the current shell, to copy it or customize the installation.          │
│ --help                -h        Show this message and exit.                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ models            List available models.                                                                                  │
│ test-categories   List available test categories.                                                                         │
│ run               Run one or more models on a test-category (same as openfunctions_evaluation).                           │
│ results           List the results available for evaluation.                                                              │
│ evaluate          Evaluate results from run of one or more models on a test-category (same as eval_runner).               │
│ scores            Display the leaderboard.                                                                                │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

➜ bfcl run -h
                                                                                                                    
 Usage: bfcl run [OPTIONS]                                                                                          
                                                                                                                    
 Run one or more models on a test-category (same as openfunctions_evaluation).                                      
                                                                                                                    
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --model                           TEXT     A list of model names to evaluate.                                    │
│                                            [default: gorilla-openfunctions-v2]                                   │
│ --test-category                   TEXT     A list of test categories to run the evaluation on. [default: all]    │
│ --api-sanity-check        -c               Perform the REST API status sanity check before running the           │
│                                            evaluation.                                                           │
│ --temperature                     FLOAT    The temperature parameter for the model. [default: 0.001]             │
│ --top-p                           FLOAT    The top-p parameter for the model. [default: 1.0]                     │
│ --max-tokens                      INTEGER  The maximum number of tokens for the model. [default: 1200]           │
│ --num-gpus                        INTEGER  The number of GPUs to use. [default: 1]                               │
│ --timeout                         INTEGER  The timeout for the model in seconds. [default: 60]                   │
│ --num-threads                     INTEGER  The number of threads to use. [default: 1]                            │
│ --gpu-memory-utilization          FLOAT    The GPU memory utilization. [default: 0.9]                            │
│ --help                    -h               Show this message and exit.                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


➜ bfcl evaluate -h
                                                                                                                    
 Usage: bfcl evaluate [OPTIONS]                                                                                     
                                                                                                                    
 Evaluate results from run of one or more models on a test-category (same as eval_runner).                          
                                                                                                                    
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *  --model                     TEXT  A list of model names to evaluate. [default: None] [required]               │
│ *  --test-category             TEXT  A list of test categories to run the evaluation on. [default: None]         │
│                                      [required]                                                                  │
│    --api-sanity-check  -c            Perform the REST API status sanity check before running the evaluation.     │
│    --help              -h            Show this message and exit.                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### CODE REVIEW

**Comment by HuanzhiMao** [comment]
Hi @mattf,

Thank you so much for your PR and welcome! I really appreciate your contribution – this feature has been on our TODO list for a while, and it’s great to see it implemented.

I noticed a few TODOs left in the code. I'll take care of finishing those up and handle any merge conflicts. After that, we’ll be ready to move forward!

**Comment by mattf** [comment]
@HuanzhiMao i'm glad you like it. i've a few more commands i'll push up.

**Comment by HuanzhiMao** [comment]
> @HuanzhiMao i'm glad you like it. i've a few more commands i'll push up.

Perfect.

**Comment by mattf** [comment]
my plan was to put a simple cli around the runner / evaluator / model definition code and then propose refactoring changes to make the cli simpler.

i've found the cli helpful for my runs, which means it's only had one user.

**Comment by HuanzhiMao** [comment]
I agree. CLI entries will be easier than `cd` into different directories and then run each script via `python xxx`.

**Comment by HuanzhiMao** [comment]
@mattf, I have resolved all the TODOs in the code and polished it a bit. Anything else you would like to add before we merge this PR?

ps, I changed `bfcl run` to `bfcl generate` for a more intuitive name.

**Review by HuanzhiMao — APPROVED** [review]

**Review by CharlieJCJ — APPROVED** [review]
Tested, suggested fixes in `bfcl generate` with consistent `.env` path. Functionalities works for my local testings. 

The CLI looks super clean! Love it @mattf, and thanks @HuanzhiMao for code changes.

**Review by CharlieJCJ — APPROVED** [review]
Re-tested on the same commands. LGTM

**Review by Fanjia-Yan — APPROVED** [review]

**Review by ShishirPatil — APPROVED** [review]

**Pull request merged**
