### PR TITLE
Quantized Gorilla

### LINKED ISSUE #77: [feature] Run gorilla locally without GPUs 🦍
Today, Gorilla end-points run on UC Berkeley hosted servers 🐻  When you try our colab, or our chat completion API, or the CLI tool, it hits our GPUs for inference. A popular ask among our users is to run Gorilla locally on Macbooks/Linux/WSL. 

**Describe the solution you'd like:**
Have the model(s) running locally on MPS/CPU/GPU and listening to a port. All the current gorilla end-points can then just hit `localhost` to get the response to any given prompt. 

**Additional context:**
Here is an application that would immediately use it: https://github.com/gorilla-llm/gorilla-cli
Given, we have LLaMA models, these should be plug-and-play: [ggerganov/llama.cpp](https://github.com/ggerganov/llama.cpp) and [karpathy/llama2.c](https://github.com/karpathy/llama2.c)
Also relevant: https://huggingface.co/TheBloke/gorilla-7B-GPTQ

Update 1: If you happen to have an RTX, or V100 or A100 or H100, you can use Gorilla today without any latency hit. The goal of this enhancement is to help those who may not have access to and greatest GPUs.

### PR DESCRIPTION
**Pull request by CharlieJCJ**
Resolved #77 , demo displaying local inference with textwebui.

K-quantized gorilla models can be found on [Huggingface](https://huggingface.co/gorilla-llm): [Llama-based](https://huggingface.co/gorilla-llm/gorilla-7b-hf-v1-gguf), [MPT-Based](https://huggingface.co/gorilla-llm/gorilla-mpt-7b-hf-v0-gguf), [Falcon-Based](https://huggingface.co/gorilla-llm/gorilla-falcon-7b-hf-v0-gguf), [`gorilla-openfunctions-v0-gguf`](https://huggingface.co/gorilla-llm/gorilla-openfunctions-v0-gguf), [`gorilla-openfunctions-v1-gguf`](https://huggingface.co/gorilla-llm/gorilla-openfunctions-v1-gguf)

A tutorial walkthrough on how to quantize model using llama.cpp with different quantization methods documented in [Colab](https://colab.research.google.com/drive/1JP_MN-J1rODo9k_-dR_9c9EnZRCfcVNe?usp=sharing).

Running local inference with Gorilla on a clean interface is simple. Demoed using [text-generation-webui](https://github.com/oobabooga/text-generation-webui), add your desired models, and run inference. 

More details in `/inference` README

Co-authored-by: Pranav Ramesh <pranramesh@users.noreply.github.com>

### CODE REVIEW

**Comment by ShishirPatil** [comment]
Thanks for the PR @CharlieJCJ and @pranramesh! 

Did you get a chance to test all the three models? I remember for Falcon and MPT they needed some minor tweaks. So, good to test they work - functionally, and the outputs make logical sense. 

Also, while you are at it, do you mind quantizing the `openfunctions-v0` and `openfunctions-v1`as well? You don't have to have the inference scripts ready now. 

Rest of it looks good, I'll go ahead and merge.

**Comment by CharlieJCJ** [comment]
Yep, I'll take care of quantizing `openfunctions-v0` and `openfunctions-v1`, and add their links to README as well in a day. I've tested MPT and Falcon ones, and their outputs are double checked.

**Comment by CharlieJCJ** [comment]
`openfunctions-v0` and `openfunctions-v1` quantized versions generated and uploaded.

K-quantized `gorilla-openfunctions-v0` and `gorilla-openfunctions-v1` models can be found on [Huggingface](https://huggingface.co/gorilla-llm): [`gorilla-openfunctions-v0-gguf`](https://huggingface.co/gorilla-llm/gorilla-openfunctions-v0-gguf), [`gorilla-openfunctions-v1-gguf`](https://huggingface.co/gorilla-llm/gorilla-openfunctions-v1-gguf)

**Review by ShishirPatil — APPROVED** [review]
LGTM. 

One potential follow-up is to benchmark the performance of these models with respect to the full precision ones.

**Pull request merged**
